<?php

namespace App\Http\Middleware;

use Closure;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;

/**
 * Dynamic rendering: serve a prerendered static HTML snapshot to CRAWLERS only
 * (Googlebot, ChatGPT, Gemini, link-preview bots…), so they get fully-rendered
 * content (H1, body, prices, FAQ) without executing JavaScript.
 *
 * Real users are never affected: the middleware only acts when (1) the request is
 * a GET from a known bot user-agent AND (2) a snapshot file exists for the path.
 * In every other case it is a pure pass-through - the live Inertia/Vue SPA is
 * served exactly as before. The app's behaviour is therefore unchanged for humans.
 *
 * Snapshots are generated by scripts/prerender.mjs into public/prerendered/.
 */
class ServePrerendered
{
    /**
     * User-agent fragments identifying crawlers we want to serve static HTML to.
     */
    private const BOT_PATTERN = '/(googlebot|bingbot|slurp|duckduckbot|baiduspider|yandex|sogou|exabot|'
        .'facebookexternalhit|facebot|ia_archiver|linkedinbot|twitterbot|slackbot|whatsapp|telegrambot|'
        .'discordbot|pinterest|redditbot|applebot|petalbot|bytespider|'
        .'gptbot|chatgpt-user|oai-searchbot|ccbot|claudebot|claude-web|anthropic-ai|'
        .'perplexitybot|perplexity-user|google-extended|googleother|amazonbot|cohere-ai|mistralai|'
        // Robots d'IA ajoutés le 2026-08-08. Ils recevaient jusque-là la coquille
        // du SPA, donc un titre « faktur.lu » et aucun contenu : indexés pour
        // rien. Constaté sur meta-externalagent et youbot en production.
        .'meta-externalagent|meta-externalfetcher|duckassistbot|youbot|ai2bot|'
        .'timpibot|diffbot|omgilibot|webzio-extended|google-cloudvertexbot)/i';

    public function handle(Request $request, Closure $next): Response
    {
        if ($this->shouldServeSnapshot($request)) {
            $file = $this->snapshotPath($request);
            if ($file !== null && is_file($file)) {
                return response(file_get_contents($file), 200, [
                    'Content-Type' => 'text/html; charset=UTF-8',
                    // Mark the response so we can confirm dynamic rendering in logs/headers.
                    'X-Prerendered' => '1',
                ]);
            }
        }

        return $next($request);
    }

    private function shouldServeSnapshot(Request $request): bool
    {
        if (! $request->isMethod('GET')) {
            return false;
        }

        $ua = (string) $request->userAgent();
        if ($ua === '' || ! preg_match(self::BOT_PATTERN, $ua)) {
            return false;
        }

        // Never intercept Inertia XHR navigations or asset requests.
        if ($request->headers->has('X-Inertia') || $request->ajax()) {
            return false;
        }

        return true;
    }

    /**
     * Resolve the snapshot file for the request path, with strict path-traversal
     * protection. Returns null if the path is not eligible.
     */
    private function snapshotPath(Request $request): ?string
    {
        $path = trim($request->path(), '/'); // Laravel path() has no leading slash, no query
        $path = $path === '' ? 'root' : $path;

        // Allow only safe URL segments - blocks "..", encoded traversal, etc.
        if (! preg_match('#^[a-zA-Z0-9\-_/]+$#', $path)) {
            return null;
        }

        return public_path("prerendered/{$path}/index.html");
    }
}
